### ISSUE TITLE
Thank for this repo

### ISSUE THREAD

**Issue by apiel** [rafamj/elecmidi#1]
Your repo helped me a lot to implement my web UI for electribe 2.
You can find my code there: https://github.com/apiel/electribe-ui

You will find some info to parse the data (even if I got lot inspiration from your code :p ), have a look especially at https://github.com/apiel/electribe-core

**Comment by rafamj** [comment]
You are welcome. I tried to execute electribe-ui, but my browser doesn't have support for midi. I will have to search a plugin.

**Comment by apiel** [comment]
I used chrome to develop it, web midi is still not compatible with many browser, see https://developer.mozilla.org/en-US/docs/Web/API/MIDIInput and it work only for E2 not E2s

**Comment by rafamj** [comment]
I can see now the image of the UI. It is nice to be able to see all parameters at once.
